// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $products_index from "./routes/products/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Navbar_index from "./islands/Navbar/index.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/products/index.tsx": $products_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Navbar/index.tsx": $Navbar_index,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
