// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_dash_index from "./routes/admin-dash/index.tsx";
import * as $api_auth_set_cookie from "./routes/api/auth/set-cookie.tsx";
import * as $api_courses_course from "./routes/api/courses/course.tsx";
import * as $api_jwt_refresh from "./routes/api/jwt/refresh.tsx";
import * as $api_jwt_token from "./routes/api/jwt/token.tsx";
import * as $api_modules_module from "./routes/api/modules/module.tsx";
import * as $api_orders_create from "./routes/api/orders/create.tsx";
import * as $api_student_user from "./routes/api/student/user.ts";
import * as $api_user_user from "./routes/api/user/user.tsx";
import * as $api_users_user from "./routes/api/users/user.tsx";
import * as $auth_redirect_index from "./routes/auth-redirect/index.tsx";
import * as $checkout_index from "./routes/checkout/index.tsx";
import * as $courses_id_ from "./routes/courses/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $login_index from "./routes/login/index.tsx";
import * as $orders_index from "./routes/orders/index.tsx";
import * as $products_index from "./routes/products/index.tsx";
import * as $user_dash_index from "./routes/user-dash/index.tsx";
import * as $work_with_me_index from "./routes/work-with-me/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Navbar_index from "./islands/Navbar/index.tsx";
import * as $ShowProducts_index from "./islands/ShowProducts/index.tsx";
import * as $admin_adminActions_index from "./islands/admin/adminActions/index.ts";
import * as $admin_adminActions_index_1 from "./islands/admin/adminActions/index.tsx";
import * as $admin_adminActions_studentsAsyncActions_studentAsyncActions from "./islands/admin/adminActions/studentsAsyncActions/studentAsyncActions.ts";
import * as $admin_courses_courseDetails from "./islands/admin/courses/courseDetails.tsx";
import * as $admin_courses_courses from "./islands/admin/courses/courses.tsx";
import * as $admin_courses_createCourse from "./islands/admin/courses/createCourse.tsx";
import * as $admin_courses_partsOfCourseDetails_modulesTab from "./islands/admin/courses/partsOfCourseDetails/modulesTab.tsx";
import * as $admin_courses_partsOfCourseDetails_overviewCards from "./islands/admin/courses/partsOfCourseDetails/overviewCards.tsx";
import * as $admin_courses_partsOfCourseDetails_students from "./islands/admin/courses/partsOfCourseDetails/students.tsx";
import * as $admin_createUser from "./islands/admin/createUser.tsx";
import * as $admin_dashboardAdmin from "./islands/admin/dashboardAdmin.tsx";
import * as $admin_editModule from "./islands/admin/editModule.tsx";
import * as $admin_header from "./islands/admin/header.tsx";
import * as $admin_index from "./islands/admin/index.tsx";
import * as $admin_modalToCreateModule from "./islands/admin/modalToCreateModule.tsx";
import * as $admin_module_editModule from "./islands/admin/module/editModule.tsx";
import * as $admin_module_modalToCreateModule from "./islands/admin/module/modalToCreateModule.tsx";
import * as $admin_module_modulePreviewModal from "./islands/admin/module/modulePreviewModal.tsx";
import * as $admin_module_modulesView from "./islands/admin/module/modulesView.tsx";
import * as $admin_modulesView from "./islands/admin/modulesView.tsx";
import * as $admin_sidebar from "./islands/admin/sidebar.tsx";
import * as $admin_students_createUser from "./islands/admin/students/createUser.tsx";
import * as $admin_students_studentDetails from "./islands/admin/students/studentDetails.tsx";
import * as $admin_students_studentUpdate from "./islands/admin/students/studentUpdate.tsx";
import * as $admin_students_students from "./islands/admin/students/students.tsx";
import * as $alerts_index from "./islands/alerts/index.tsx";
import * as $cart_index from "./islands/cart/index.tsx";
import * as $changeLanguage_index from "./islands/changeLanguage/index.tsx";
import * as $checkout_index_1 from "./islands/checkout/index.tsx";
import * as $components_spinners_spinners from "./islands/components/spinners/spinners.tsx";
import * as $helpers_TokenInitializer from "./islands/helpers/TokenInitializer.tsx";
import * as $helpers_index from "./islands/helpers/index.tsx";
import * as $helpers_tokenRedirect from "./islands/helpers/tokenRedirect.tsx";
import * as $login_index_1 from "./islands/login/index.tsx";
import * as $main_courses from "./islands/main/courses.tsx";
import * as $main_footer from "./islands/main/footer.tsx";
import * as $main_head from "./islands/main/head.tsx";
import * as $main_index from "./islands/main/index.tsx";
import * as $main_learnWithMe from "./islands/main/learnWithMe.tsx";
import * as $main_testimonials from "./islands/main/testimonials.tsx";
import * as $modal_index from "./islands/modal/index.tsx";
import * as $portafolio_index from "./islands/portafolio/index.tsx";
import * as $showOrders_showOrders from "./islands/showOrders/showOrders.tsx";
import * as $student_course_courseProgress from "./islands/student/course/courseProgress.tsx";
import * as $student_course_selectedCourse from "./islands/student/course/selectedCourse.tsx";
import * as $student_dashboardParts_renderCourses from "./islands/student/dashboardParts/renderCourses.tsx";
import * as $student_moduleCard from "./islands/student/moduleCard.tsx";
import * as $student_modulePreview from "./islands/student/modulePreview.tsx";
import * as $student_studentDashboard from "./islands/student/studentDashboard.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin-dash/index.tsx": $admin_dash_index,
    "./routes/api/auth/set-cookie.tsx": $api_auth_set_cookie,
    "./routes/api/courses/course.tsx": $api_courses_course,
    "./routes/api/jwt/refresh.tsx": $api_jwt_refresh,
    "./routes/api/jwt/token.tsx": $api_jwt_token,
    "./routes/api/modules/module.tsx": $api_modules_module,
    "./routes/api/orders/create.tsx": $api_orders_create,
    "./routes/api/student/user.ts": $api_student_user,
    "./routes/api/user/user.tsx": $api_user_user,
    "./routes/api/users/user.tsx": $api_users_user,
    "./routes/auth-redirect/index.tsx": $auth_redirect_index,
    "./routes/checkout/index.tsx": $checkout_index,
    "./routes/courses/[id].tsx": $courses_id_,
    "./routes/index.tsx": $index,
    "./routes/login/index.tsx": $login_index,
    "./routes/orders/index.tsx": $orders_index,
    "./routes/products/index.tsx": $products_index,
    "./routes/user-dash/index.tsx": $user_dash_index,
    "./routes/work-with-me/index.tsx": $work_with_me_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Navbar/index.tsx": $Navbar_index,
    "./islands/ShowProducts/index.tsx": $ShowProducts_index,
    "./islands/admin/adminActions/index.ts": $admin_adminActions_index,
    "./islands/admin/adminActions/index.tsx": $admin_adminActions_index_1,
    "./islands/admin/adminActions/studentsAsyncActions/studentAsyncActions.ts":
      $admin_adminActions_studentsAsyncActions_studentAsyncActions,
    "./islands/admin/courses/courseDetails.tsx": $admin_courses_courseDetails,
    "./islands/admin/courses/courses.tsx": $admin_courses_courses,
    "./islands/admin/courses/createCourse.tsx": $admin_courses_createCourse,
    "./islands/admin/courses/partsOfCourseDetails/modulesTab.tsx":
      $admin_courses_partsOfCourseDetails_modulesTab,
    "./islands/admin/courses/partsOfCourseDetails/overviewCards.tsx":
      $admin_courses_partsOfCourseDetails_overviewCards,
    "./islands/admin/courses/partsOfCourseDetails/students.tsx":
      $admin_courses_partsOfCourseDetails_students,
    "./islands/admin/createUser.tsx": $admin_createUser,
    "./islands/admin/dashboardAdmin.tsx": $admin_dashboardAdmin,
    "./islands/admin/editModule.tsx": $admin_editModule,
    "./islands/admin/header.tsx": $admin_header,
    "./islands/admin/index.tsx": $admin_index,
    "./islands/admin/modalToCreateModule.tsx": $admin_modalToCreateModule,
    "./islands/admin/module/editModule.tsx": $admin_module_editModule,
    "./islands/admin/module/modalToCreateModule.tsx":
      $admin_module_modalToCreateModule,
    "./islands/admin/module/modulePreviewModal.tsx":
      $admin_module_modulePreviewModal,
    "./islands/admin/module/modulesView.tsx": $admin_module_modulesView,
    "./islands/admin/modulesView.tsx": $admin_modulesView,
    "./islands/admin/sidebar.tsx": $admin_sidebar,
    "./islands/admin/students/createUser.tsx": $admin_students_createUser,
    "./islands/admin/students/studentDetails.tsx":
      $admin_students_studentDetails,
    "./islands/admin/students/studentUpdate.tsx": $admin_students_studentUpdate,
    "./islands/admin/students/students.tsx": $admin_students_students,
    "./islands/alerts/index.tsx": $alerts_index,
    "./islands/cart/index.tsx": $cart_index,
    "./islands/changeLanguage/index.tsx": $changeLanguage_index,
    "./islands/checkout/index.tsx": $checkout_index_1,
    "./islands/components/spinners/spinners.tsx": $components_spinners_spinners,
    "./islands/helpers/TokenInitializer.tsx": $helpers_TokenInitializer,
    "./islands/helpers/index.tsx": $helpers_index,
    "./islands/helpers/tokenRedirect.tsx": $helpers_tokenRedirect,
    "./islands/login/index.tsx": $login_index_1,
    "./islands/main/courses.tsx": $main_courses,
    "./islands/main/footer.tsx": $main_footer,
    "./islands/main/head.tsx": $main_head,
    "./islands/main/index.tsx": $main_index,
    "./islands/main/learnWithMe.tsx": $main_learnWithMe,
    "./islands/main/testimonials.tsx": $main_testimonials,
    "./islands/modal/index.tsx": $modal_index,
    "./islands/portafolio/index.tsx": $portafolio_index,
    "./islands/showOrders/showOrders.tsx": $showOrders_showOrders,
    "./islands/student/course/courseProgress.tsx":
      $student_course_courseProgress,
    "./islands/student/course/selectedCourse.tsx":
      $student_course_selectedCourse,
    "./islands/student/dashboardParts/renderCourses.tsx":
      $student_dashboardParts_renderCourses,
    "./islands/student/moduleCard.tsx": $student_moduleCard,
    "./islands/student/modulePreview.tsx": $student_modulePreview,
    "./islands/student/studentDashboard.tsx": $student_studentDashboard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
